ergonode_workflow_api:
    resource: '../../Application/Controller/Api/Workflow*'
    type: annotation
    prefix: /api/v1/{language}/

ergonode_status_api:
    resource: '../../Application/Controller/Api/Status*'
    type: annotation
    prefix: /api/v1/{language}
